// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Amortization.Domain.Models
{
    public partial class GetDashboardDataResult
    {
        public long? TotalLoan { get; set; }
        public long? TotalBuyer { get; set; }
        public long? TotalProject { get; set; }
    }
}
