// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Amortization.Domain.Models
{
    public partial class GetspUnitInfoResult
    {
        public string? Name { get; set; }
        public long? ProjectId { get; set; }
        public string? ProjectName { get; set; }
        public long UnitId { get; set; }
        public string? CondoUnit { get; set; }
    }
}
