// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Amortization.Domain.Models;

public partial class Loan
{
    public long LoanId { get; set; }

    public long? BuyerId { get; set; }

    public long? ProjectId { get; set; }

    public long? UnitId { get; set; }

    public double? LoanAmount { get; set; }

    public int? PaymentTerm { get; set; }

    public DateTime? PaymentStart { get; set; }

    public double? InterestRate { get; set; }

    public double? Principal { get; set; }

    public long? CreateId { get; set; }

    public DateTime? CreateDate { get; set; }

    public long? LastUpdateId { get; set; }

    public DateTime? LastUpdateDate { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();
}