// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Amortization.Domain.Models;

public partial class Project
{
    public long ProjectId { get; set; }

    public string? Name { get; set; }

    public long? CreateId { get; set; }

    public DateTime? CreateDate { get; set; }

    public long? LastUpdateId { get; set; }

    public DateTime? LastUpdateDate { get; set; }

    public virtual ICollection<Unit> Units { get; set; } = new List<Unit>();
}