// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Amortization.Domain.Models;

public partial class Schedule
{
    public long ScheduleId { get; set; }

    public long? LoanId { get; set; }

    public DateTime? PaymentDate { get; set; }

    public double? Principal { get; set; }

    public double? Interest { get; set; }

    public double? Total { get; set; }

    public double? Balance { get; set; }

    public int? No_of_Days { get; set; }

    public virtual Loan? Loan { get; set; }
}