// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Amortization.Domain.Models
{
    public partial class spGetBuyerInformationResult
    {
        public long BuyerId { get; set; }
        public long ProjectId { get; set; }
        public long? UnitId { get; set; }
        public long LoanId { get; set; }
        public string? BuyerName { get; set; }
        public string? Imprint_Id { get; set; }
        public string? Address { get; set; }
        public string? ProjectName { get; set; }
        public string? CondoUnit { get; set; }
        public double? LoanAmount { get; set; }
        public DateTime? PaymentStart { get; set; }
        public double? InterestRate { get; set; }
        public int? PaymentTerm { get; set; }
    }
}
