// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Amortization.Domain.Models
{
    public partial class spGetLoanerDropdownResult
    {
        public long BuyerId { get; set; }
        public string? Name { get; set; }
    }
}
