// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Amortization.Domain.Models;
using Microsoft.EntityFrameworkCore;

namespace Amortization.Domain.Contexts;

public partial class AmortizationDBContext : DbContext
{
    public AmortizationDBContext(DbContextOptions<AmortizationDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Buyer> Buyers { get; set; }

    public virtual DbSet<Loan> Loans { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<Schedule> Schedules { get; set; }

    public virtual DbSet<Unit> Units { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Buyer>(entity =>
        {
            entity.ToTable("Buyer");

            entity.Property(e => e.Address)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Imprint_Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastUpdateDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .HasMaxLength(150)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Loan>(entity =>
        {
            entity.ToTable("Loan");

            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.LastUpdateDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentStart).HasColumnType("datetime");
        });

        modelBuilder.Entity<Project>(entity =>
        {
            entity.ToTable("Project");

            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.LastUpdateDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Schedule>(entity =>
        {
            entity.ToTable("Schedule");

            entity.Property(e => e.PaymentDate).HasColumnType("datetime");

            entity.HasOne(d => d.Loan).WithMany(p => p.Schedules)
                .HasForeignKey(d => d.LoanId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Schedule_Loan");
        });

        modelBuilder.Entity<Unit>(entity =>
        {
            entity.ToTable("Unit");

            entity.Property(e => e.CondoUnit)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.LastUpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Buyer).WithMany(p => p.Units)
                .HasForeignKey(d => d.BuyerId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Unit_Buyer");

            entity.HasOne(d => d.Project).WithMany(p => p.Units)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Unit_Project");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}