// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Amortization.Domain.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Amortization.Domain.Contexts
{
    public partial interface IAmortizationDBContextProcedures
    {
        Task<List<GetDashboardDataResult>> GetDashboardDataAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetspUnitInfoResult>> GetspUnitInfoAsync(long? ProjectId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spAmortizationScheduleResult>> spAmortizationScheduleAsync(long? LoanId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetAllBuyerTransactionsResult>> spGetAllBuyerTransactionsAsync(long? BuyerId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetAllLoanListResult>> spGetAllLoanListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetBuyerInformationResult>> spGetBuyerInformationAsync(long? BuyerId, long? UnitId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetLoanerDropdownResult>> spGetLoanerDropdownAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
